USE bodegadrogueria;
USE drogueria;

CREATE OR REPLACE VIEW drogueria.ITEMVIEW 
AS SELECT 
`ID_ITEM`, 
`ID_REFERENCIA`,
`DESCRIPCION`, 
`ID_LINEA2`,
`ID_GRUPO2`,
`UNIMED_INV_1`,
`UNIMED_EMPAQ`,
`FACTOR_EMPAQ`,
`PESO`, 
`VOLUMEN`,
`ULTIMO_COSTO_ED`,
`FECHA_INGRESO`
FROM drogueria.ITEMS; 


CREATE OR REPLACE VIEW drogueria.CODVIEW
AS SELECT  
`ID_ITEMS`,
`ID_CODBAR`,
`UNIMED_VENTA`
FROM drogueria.COD_BARRAS;

CREATE TABLE IF NOT EXISTS `ITEMSVIEW` (
	`ID_ITEM` char(6) NOT NULL,
	`ID_REFERENCIA` char(15) DEFAULT NULL,
	`DESCRIPCION` char(40) DEFAULT NULL,
	`ID_LINEA2` char(6) DEFAULT NULL,
	`ID_GRUPO2` char(6) DEFAULT NULL,
	`UNIMED_INV_1` char(3) DEFAULT NULL,
	`UNIMED_EMPAQ` char(3) DEFAULT NULL,
	`FACTOR_EMPAQ` decimal(20,4) DEFAULT NULL,
	`PESO` decimal(20,4) DEFAULT NULL,
	`VOLUMEN` decimal(20,4) DEFAULT NULL,
	`ULTIMO_COSTO_ED` decimal(20,4) DEFAULT NULL,
	`FECHA_INGRESO` char(8) DEFAULT NULL,
	`IVA` FLOAT(20,2) 
	
) ENGINE=FEDERATED
-- ENGINE=CONNECT table_type=MYSQL
DEFAULT CHARSET=latin1
CONNECTION='mysql://user:user_pass@localhost/drogueria/ITEMVIEW';

CREATE TABLE IF NOT EXISTS `COD_BARRASVIEW` (
	`ID_ITEMS` char(6) DEFAULT NULL,
	`ID_CODBAR` char(15) BINARY DEFAULT NULL,
	`UNIMED_VENTA` char(3) DEFAULT NULL
	
)ENGINE=FEDERATED
-- ENGINE=CONNECT table_type=MYSQL
DEFAULT CHARSET=latin1
CONNECTION='mysql://user:user_pass@localhost/drogueria/CODVIEW';

INSERT INTO bodegadrogueria.ITEMS
(ID_ITEM,ID_REFERENCIA,DESCRIPCION,ID_LINEA2,ID_GRUPO2,UNIMED_INV_1,UNIMED_EMPAQ,FACTOR_EMPAQ,PESO,VOLUMEN,ULTIMO_COSTO_ED,FECHA_INGRESO,IVA)
(SELECT *
FROM bodegadrogueria.ITEMSVIEW)
ON DUPLICATE KEY UPDATE
ITEMS.DESCRIPCION=ITEMSVIEW.DESCRIPCION,
ITEMS.ID_LINEA2=ITEMSVIEW.ID_LINEA2,
ITEMS.ID_GRUPO2=ITEMSVIEW.ID_GRUPO2,
ITEMS.UNIMED_INV_1=ITEMSVIEW.UNIMED_INV_1,
ITEMS.UNIMED_EMPAQ=ITEMSVIEW.UNIMED_EMPAQ,
ITEMS.FACTOR_EMPAQ=ITEMSVIEW.FACTOR_EMPAQ,
ITEMS.PESO=ITEMSVIEW.PESO,
ITEMS.VOLUMEN=ITEMSVIEW.VOLUMEN,
ITEMS.ULTIMO_COSTO_ED=ITEMSVIEW.ULTIMO_COSTO_ED,
ITEMS.FECHA_INGRESO=ITEMSVIEW.FECHA_INGRESO,
ITEMS.IVA=ITEMSVIEW.IVA;


INSERT INTO bodegadrogueria.COD_BARRAS
(SELECT *
FROM bodegadrogueria.COD_BARRASVIEW)
ON DUPLICATE KEY UPDATE
COD_BARRAS.UNIMED_VENTA=COD_BARRASVIEW.UNIMED_VENTA;